version: '3.8'

services:
  web:
    build: ./
    command: python3.10 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/app/
    ports:
      - ${SERVER_PORT}:8000
    env_file:
      - ./.env
    depends_on:
      - db
    restart: always
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always

volumes:
  postgres_data: